/**
 * Use the following command to generate the TypeScript interface for your .envx file:
 * > npx dotenvxjs types
 */
import { Envx } from "./envx";

import { getEnvx, loadEnvx } from "../src";

// --- ad environment variables into process.env (makes them accessible globally)--- //
loadEnvx("examples/.envx");

// --- If you prefer not to use loadEnvx and want to work directly with typed environment variables (using the interface generated by `npx dotenvxjs types`) --- //
const env = getEnvx<Envx>("./examples/.envx");

console.log("API_TOKEN: ", process.env.API_TOKEN);
console.log("API_URL: ", process.env.API_URL);

console.log("FULL_API_URL: ", process.env.FULL_API_URL);
console.log("DATABASE_NAME: ", env.DATABASE_NAME);

console.log("PORT: ", process.env.PORT);
console.log("NODE_ENV: ", process.env.NODE_ENV);

console.log("WEBSITE_URL: ", env.WEBSITE_URL);
console.log("BASE: ", env.BASE);

if (env.DEV_MODE == false) {
  console.log("DEV_MODE=false");
} else {
  console.log("DEV_MODE=true");
}
